services:
  mariadb:
    image: mariadb:lts
    container_name: ${mariadb_container}
    environment:
      MYSQL_ROOT_PASSWORD: ${db_root_password}
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_password}
    volumes:
      #- ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
      - ./custom-entrypoint.sh:/custom-entrypoint.sh
    # entrypoint: ["bash", "/custom-entrypoint.sh"]
    # command: --log-bin --log-basename=mariadb
    ports:
      - "3306:3306"
    networks:
      - single-nx

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${mariadb_container}
      PMA_DATABASE: ${db_name}
      PMA_USER: ${db_user}
      PMA_PASSWORD: ${db_password}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - single-nx

networks:
  single-nx:
    name: single-nx
    driver: bridge